# Generated by Django 5.1.2 on 2024-10-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='expiration_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('EXP', 'Expired')], default='ACT', max_length=3),
        ),
    ]
