# Generated by Django 5.1.2 on 2024-11-09 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Courses/Images/')),
                ('video', models.FileField(upload_to='Courses/Videos/')),
                ('price_status', models.CharField(choices=[('FREE', 'Free'), ('PAID', 'Paid')], default='FREE', max_length=5)),
                ('price', models.BigIntegerField(default=0)),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='DescriptionCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Description', to='Courses.course')),
            ],
            options={
                'verbose_name': 'Description Course',
                'verbose_name_plural': 'Descriptions Course',
            },
        ),
        migrations.CreateModel(
            name='FAQCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FAQ', to='Courses.course')),
            ],
            options={
                'verbose_name': 'FAQ Course',
                'verbose_name_plural': 'FAQs Course',
            },
        ),
    ]
